version: '3.4'

services:
  php:
    build:
      context: .
      target: news_paring_service
    depends_on:
      - rabbitmq
      - db
    volumes:
      - ./:/srv

  nginx:
    build:
      context: .
      target: news_paring_service_nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/public:ro
    ports:
      - "80:80"
      - "81:8080"

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile-rabbitmq
    hostname: news_paring_service-node-1
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  db:
    image: mysql:8.0
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: news
      MYSQL_USER: news
      MYSQL_PASSWORD: newspw

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  db:
    driver: local

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
