services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    App\Core\Test\:
        resource: '../src/Core/Test/*'
          
    # Allowing access to private services
    Symfony\Contracts\HttpClient\HttpClientInterface: '@App\Core\Test\HttpClient\MockHttpClient'
